### ISSUE TITLE
DeprecationWarnings on start from simple-node-logger

### ISSUE THREAD

**Issue by acortelyou** [p10tyr/rtsp-to-onvif#9]
This doesn't seem to causing a problem, just filing an issue to track eventual fix.

Looks like either simple-node-logger needs to be updated or replaced with something else.

```
(node:1) [DEP0047] DeprecationWarning: The `util.isDate` API is deprecated.  Please use `arg instanceof Date` instead.
(node:1) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
```

```
(node:26) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.                                               
    at AbstractAppender.formatMessage (/app/node_modules/simple-node-logger/lib/AbstractAppender.js:65:18)                                                        
    at AbstractAppender.formatEntry (/app/node_modules/simple-node-logger/lib/AbstractAppender.js:45:27)                                                          
    at ConsoleAppender.formatter (/app/node_modules/simple-node-logger/lib/ConsoleAppender.js:34:33)                                                              
    at ConsoleAppender.write (/app/node_modules/simple-node-logger/lib/ConsoleAppender.js:45:30)                                                                  
    at /app/node_modules/simple-node-logger/lib/Logger.js:42:26                  
    at Array.forEach (<anonymous>)                                               
    at /app/node_modules/simple-node-logger/lib/Logger.js:41:23                  
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11
)                   
```
```
(node:26) [DEP0047] DeprecationWarning: The `util.isDate` API is deprecated.  Please use `arg instanceof Date` instead.                                           
    at /app/node_modules/simple-node-logger/lib/AbstractAppender.js:67:26        
    at Array.map (<anonymous>)                                                   
    at AbstractAppender.formatMessage (/app/node_modules/simple-node-logger/lib/AbstractAppender.js:66:30)                                                        
    at AbstractAppender.formatEntry (/app/node_modules/simple-node-logger/lib/AbstractAppender.js:45:27)                                                          
    at ConsoleAppender.formatter (/app/node_modules/simple-node-logger/lib/ConsoleAppender.js:34:33)                                                              
    at ConsoleAppender.write (/app/node_modules/simple-node-logger/lib/ConsoleAppender.js:45:30)                                                                  
    at /app/node_modules/simple-node-logger/lib/Logger.js:42:26                  
    at Array.forEach (<anonymous>)                                               
    at /app/node_modules/simple-node-logger/lib/Logger.js:41:23                  
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11
)
```

**Comment by p10tyr** [comment]
Yes I have seen that. That is coming from Simple-Node-Logger (server-side commonJS).. that package hasn't been updated for a few years it would need a bump on that side. There seem to be a few dependaBOT  PR's there.. but as usual no owner to merge it them 😢 

https://github.com/darrylwest/simple-node-logger/pulls

**Comment by p10tyr** [comment]
I did a PR here to use my fixed fork in the packages JSON https://github.com/p10tyr/rtsp-to-onvif/pull/12

I have never done that before.. so... hope it works 😄

**Comment by p10tyr** [comment]
I fixed the original deprecation message but un earthed a ton of old libraries shouting for help 🆘 

```javascript
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@2.6.3: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.0: Glob versions prior to v9 are no longer supported
npm warn deprecated node-uuid@1.4.8: Use uuid module instead
npm warn deprecated eslint@6.8.0: This version is no longer supported. Please see https://eslint.org/version-support for other options.
```
